[build]
  command = "pip install -r requirements.txt && gunicorn app:app"
  publish = "public"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true

[dev]
  command = "python app.py"
  port = 8080
